services:
  dnaxcat-discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: dnaxcat-discord-bot
    container_name: dnaxcat-discord-bot
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
    volumes:
      - ./temp/music:/app/temp/music
      - ./logs:/app/logs
    restart: unless-stopped
    tty: true
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
